const CARDS = [
  ['The Fool', 'New beginnings, spontaneity, a leap of faith.', 'Recklessness, hesitation, fear of the unknown.'],
  ['The Magician', 'Manifestation, willpower, resourcefulness.', 'Manipulation, scattered energy, untapped talent.'],
  ['The High Priestess', 'Intuition, mystery, inner knowing.', 'Secrets withheld, ignored instinct, disconnection.'],
  ['The Empress', 'Abundance, nurturing, creativity.', 'Creative block, dependence, neglected self-care.'],
  ['The Emperor', 'Structure, authority, stability.', 'Domination, rigidity, loss of control.'],
  ['The Hierophant', 'Tradition, guidance, shared belief.', 'Rebellion, dogma questioned, personal truth.'],
  ['The Lovers', 'Union, choice, alignment of values.', 'Disharmony, misalignment, avoided decision.'],
  ['The Chariot', 'Determination, control, forward drive.', 'Loss of direction, opposition, scattered will.'],
  ['Strength', 'Courage, gentle power, inner resolve.', 'Self-doubt, raw emotion, depleted strength.'],
  ['The Hermit', 'Introspection, solitude, inner guidance.', 'Isolation, withdrawal, lost bearings.'],
  ['Wheel of Fortune', 'Turning point, fate, cycles.', 'Bad luck, resistance to change, stuck cycle.'],
  ['Justice', 'Fairness, truth, accountability.', 'Injustice, dishonesty, unaccountability.'],
  ['The Hanged Man', 'Surrender, new perspective, pause.', 'Stalling, resistance, needless sacrifice.'],
  ['Death', 'Endings, transformation, release.', 'Fear of change, clinging, stagnation.'],
  ['Temperance', 'Balance, moderation, patience.', 'Excess, imbalance, discord.'],
  ['The Devil', 'Attachment, temptation, shadow self.', 'Release, reclaiming power, breaking chains.'],
  ['The Tower', 'Sudden upheaval, revelation, collapse.', 'Averted disaster, fear of change, delayed chaos.'],
  ['The Star', 'Hope, renewal, serene faith.', 'Discouragement, lost faith, disconnection.'],
  ['The Moon', 'Illusion, intuition, the unknown.', 'Confusion lifting, released fear, clarity returning.'],
  ['The Sun', 'Joy, success, vitality, clarity.', 'Temporary gloom, blocked joy, over-optimism.'],
  ['Judgement', 'Awakening, reckoning, renewal.', 'Self-doubt, avoided reckoning, harsh judgment.'],
  ['The World', 'Completion, wholeness, fulfillment.', 'Loose ends, delay, incomplete closure.'],
  ['Ace of Wands', 'Inspiration, spark, new passion.', 'Delays, false start, lost drive.'],
  ['Two of Wands', 'Planning, decisions, future vision.', 'Fear of unknown, poor planning, playing safe.'],
  ['Three of Wands', 'Expansion, foresight, momentum.', 'Delays, obstacles, limited vision.'],
  ['Four of Wands', 'Celebration, harmony, homecoming.', 'Instability, tension, canceled celebration.'],
  ['Five of Wands', 'Conflict, competition, friction.', 'Avoiding conflict, resolution, inner tension.'],
  ['Six of Wands', 'Victory, recognition, confidence.', 'Setback, doubt, lack of recognition.'],
  ['Seven of Wands', 'Defense, perseverance, standing firm.', 'Overwhelm, giving up, yielding ground.'],
  ['Eight of Wands', 'Speed, movement, swift news.', 'Delays, frustration, scattered energy.'],
  ['Nine of Wands', 'Resilience, persistence, last stand.', 'Exhaustion, defensiveness, burnout.'],
  ['Ten of Wands', 'Burden, responsibility, hard work.', 'Release, delegation, letting go of load.'],
  ['Page of Wands', 'Exploration, enthusiasm, discovery.', 'Aimlessness, hesitation, unformed ideas.'],
  ['Knight of Wands', 'Action, adventure, bold energy.', 'Impulsiveness, recklessness, delays.'],
  ['Queen of Wands', 'Confidence, warmth, magnetism.', 'Self-doubt, insecurity, withdrawal.'],
  ['King of Wands', 'Vision, leadership, bold direction.', 'Impulsiveness, domineering, overreach.'],
  ['Ace of Cups', 'New love, emotional opening, compassion.', 'Blocked emotion, emptiness, guardedness.'],
  ['Two of Cups', 'Partnership, connection, mutual love.', 'Imbalance, discord, broken bond.'],
  ['Three of Cups', 'Friendship, celebration, community.', 'Overindulgence, gossip, isolation.'],
  ['Four of Cups', 'Apathy, contemplation, a missed offer.', 'Renewed interest, awareness, acceptance.'],
  ['Five of Cups', 'Loss, regret, grief.', 'Acceptance, healing, moving on.'],
  ['Six of Cups', 'Nostalgia, innocence, reunion.', 'Stuck in the past, clinging, moving forward.'],
  ['Seven of Cups', 'Choices, fantasy, illusion.', 'Clarity, decisiveness, a reality check.'],
  ['Eight of Cups', 'Walking away, seeking meaning, departure.', 'Fear of change, aimless drifting, staying stuck.'],
  ['Nine of Cups', 'Contentment, wishes fulfilled, satisfaction.', 'Dissatisfaction, indulgence, an unmet wish.'],
  ['Ten of Cups', 'Harmony, joy, lasting happiness.', 'Broken harmony, misalignment, strained bonds.'],
  ['Page of Cups', 'Creativity, intuition, a tender message.', 'Emotional immaturity, blocked feeling, doubt.'],
  ['Knight of Cups', 'Romance, charm, following the heart.', 'Moodiness, unrealistic ideals, disappointment.'],
  ['Queen of Cups', 'Compassion, emotional depth, care.', 'Emotional overwhelm, insecurity, martyrdom.'],
  ['King of Cups', 'Emotional balance, calm, wisdom.', 'Moodiness, suppression, manipulation.'],
  ['Ace of Swords', 'Clarity, breakthrough, truth.', 'Confusion, misused power, clouded judgment.'],
  ['Two of Swords', 'Stalemate, a difficult choice, avoidance.', 'Indecision resolved, overwhelm, released tension.'],
  ['Three of Swords', 'Heartbreak, sorrow, painful truth.', 'Healing, forgiveness, releasing pain.'],
  ['Four of Swords', 'Rest, recovery, quiet reflection.', 'Restlessness, burnout, reawakening.'],
  ['Five of Swords', 'Conflict, defeat, a hollow victory.', 'Reconciliation, making amends, release.'],
  ['Six of Swords', 'Transition, moving on, calmer waters.', 'Resistance to change, an unfinished journey.'],
  ['Seven of Swords', 'Deception, strategy, acting alone.', 'Confession, exposure, conscience.'],
  ['Eight of Swords', 'Restriction, self-limitation, feeling trapped.', 'Freedom, new perspective, release.'],
  ['Nine of Swords', 'Anxiety, worry, sleepless fear.', 'Hope returning, released worry, recovery.'],
  ['Ten of Swords', 'A painful ending, rock bottom, collapse.', 'Recovery, survival, the worst is over.'],
  ['Page of Swords', 'Curiosity, vigilance, new ideas.', 'Scattered thoughts, gossip, hasty words.'],
  ['Knight of Swords', 'Ambition, drive, decisive action.', 'Recklessness, impatience, aggression.'],
  ['Queen of Swords', 'Clarity, honesty, an independent mind.', 'Coldness, harsh judgment, bitterness.'],
  ['King of Swords', 'Authority, intellect, clear judgment.', 'Manipulation, coldness, misuse of logic.'],
  ['Ace of Pentacles', 'Opportunity, prosperity, a new venture.', 'A missed chance, insecurity, poor planning.'],
  ['Two of Pentacles', 'Balance, adaptability, juggling priorities.', 'Overwhelm, disorganization, imbalance.'],
  ['Three of Pentacles', 'Collaboration, skill, craftsmanship.', 'Discord, poor teamwork, lack of quality.'],
  ['Four of Pentacles', 'Security, control, saving.', 'Greed, clinging, releasing control.'],
  ['Five of Pentacles', 'Hardship, insecurity, isolation.', 'Recovery, renewed hope, help arriving.'],
  ['Six of Pentacles', 'Generosity, giving and receiving, balance.', 'Strings attached, inequality, debt.'],
  ['Seven of Pentacles', 'Patience, investment, long-term growth.', 'Impatience, poor return, wasted effort.'],
  ['Eight of Pentacles', 'Diligence, mastery, dedication.', 'Perfectionism, uninspired work, cut corners.'],
  ['Nine of Pentacles', 'Abundance, independence, self-reward.', 'Overwork, financial dependence, hollow luxury.'],
  ['Ten of Pentacles', 'Legacy, wealth, family foundation.', 'Instability, loss, fleeting success.'],
  ['Page of Pentacles', 'Ambition, study, a new opportunity.', 'Lack of focus, procrastination, a missed lesson.'],
  ['Knight of Pentacles', 'Reliability, diligence, steady effort.', 'Stagnation, dullness, over-caution.'],
  ['Queen of Pentacles', 'Nurturing, practicality, abundance.', 'Self-neglect, imbalance, smothering.'],
  ['King of Pentacles', 'Prosperity, security, disciplined success.', 'Greed, materialism, being controlling.'],
];

export const DECK = CARDS.map(([name, upright, reversed], id) => ({
  id,
  name,
  image: `design/assets/cards/${id} ${name}.jpg`,
  upright,
  reversed,
}));
